/** @format */

import React, { useEffect, useState } from "react";
import Header from "../../Components/Header/Header";
import { TrendingRepo, TrendingDev } from "../../Constants/CommonConstants";
import TrendingList from "../../Components/TrendingList/TrendingList";

export default function HomePage() {
  const [trendingRepo, setTrendingRepo] = useState<TrendingRepo[]>();
  const [trendingDeveloper, setTrendingDeveloper] = useState<TrendingDev[]>();
  useEffect(() => {
    setTrendingRepo([
      {
        rank: 1,
        username: "DataTalksClub",
        repositoryName: "data-engineering-zoomcamp",
        url: "https://github.com/DataTalksClub/data-engineering-zoomcamp",
        description: "Code for Data Engineer Zoomcamp course",
        language: "Jupyter Notebook",
        languageColor: "#DA5B0B",
        totalStars: 1910,
        forks: 254,
        starsSince: 456,
        since: "daily",
        builtBy: [
          {
            username: "sejalv",
            url: "https://github.com/sejalv",
            avatar: "https://avatars.githubusercontent.com/u/9307691?s=40&v=4",
          },
          {
            username: "alexeygrigorev",
            url: "https://github.com/alexeygrigorev",
            avatar: "https://avatars.githubusercontent.com/u/875246?s=40&v=4",
          },
          {
            username: "Victoriapm",
            url: "https://github.com/Victoriapm",
            avatar: "https://avatars.githubusercontent.com/u/4315804?s=40&v=4",
          },
          {
            username: "AnkushKhanna",
            url: "https://github.com/AnkushKhanna",
            avatar: "https://avatars.githubusercontent.com/u/3662357?s=40&v=4",
          },
        ],
      },
      {
        rank: 2,
        username: "NVlabs",
        repositoryName: "instant-ngp",
        url: "https://github.com/NVlabs/instant-ngp",
        description:
          "Instant neural graphics primitives: lightning fast NeRF and more",
        language: "Cuda",
        languageColor: "#3A4E3A",
        totalStars: 1641,
        forks: 113,
        starsSince: 464,
        since: "daily",
        builtBy: [
          {
            username: "Tom94",
            url: "https://github.com/Tom94",
            avatar: "https://avatars.githubusercontent.com/u/4923655?s=40&v=4",
          },
          {
            username: "mjc619",
            url: "https://github.com/mjc619",
            avatar: "https://avatars.githubusercontent.com/u/8377727?s=40&v=4",
          },
          {
            username: "pwais",
            url: "https://github.com/pwais",
            avatar: "https://avatars.githubusercontent.com/u/218145?s=40&v=4",
          },
          {
            username: "mmalex",
            url: "https://github.com/mmalex",
            avatar: "https://avatars.githubusercontent.com/u/715855?s=40&v=4",
          },
          {
            username: "myagues",
            url: "https://github.com/myagues",
            avatar: "https://avatars.githubusercontent.com/u/25502655?s=40&v=4",
          },
        ],
      },
      {
        rank: 3,
        username: "XProger",
        repositoryName: "OpenLara",
        url: "https://github.com/XProger/OpenLara",
        description: "Classic Tomb Raider open-source engine",
        language: "C",
        languageColor: "#555555",
        totalStars: 3173,
        forks: 253,
        starsSince: 216,
        since: "daily",
        builtBy: [
          {
            username: "XProger",
            url: "https://github.com/XProger",
            avatar: "https://avatars.githubusercontent.com/u/796763?s=40&v=4",
          },
          {
            username: "Gh0stBlade",
            url: "https://github.com/Gh0stBlade",
            avatar: "https://avatars.githubusercontent.com/u/6951235?s=40&v=4",
          },
          {
            username: "vanfanel",
            url: "https://github.com/vanfanel",
            avatar: "https://avatars.githubusercontent.com/u/837585?s=40&v=4",
          },
          {
            username: "laripette",
            url: "https://github.com/laripette",
            avatar: "https://avatars.githubusercontent.com/u/77933011?s=40&v=4",
          },
          {
            username: "cochrane",
            url: "https://github.com/cochrane",
            avatar: "https://avatars.githubusercontent.com/u/2102135?s=40&v=4",
          },
        ],
      },
      {
        rank: 4,
        username: "rickwierenga",
        repositoryName: "sci-hub-injector",
        url: "https://github.com/rickwierenga/sci-hub-injector",
        description: "Adds SciHub links to popular publisher websites",
        language: null,
        languageColor: null,
        totalStars: 547,
        forks: 39,
        starsSince: 155,
        since: "daily",
        builtBy: [
          {
            username: "rickwierenga",
            url: "https://github.com/rickwierenga",
            avatar: "https://avatars.githubusercontent.com/u/36956818?s=40&v=4",
          },
          {
            username: "mahalde",
            url: "https://github.com/mahalde",
            avatar: "https://avatars.githubusercontent.com/u/39100405?s=40&v=4",
          },
          {
            username: "GrzegorzWidla",
            url: "https://github.com/GrzegorzWidla",
            avatar: "https://avatars.githubusercontent.com/u/1068754?s=40&v=4",
          },
          {
            username: "tbodt",
            url: "https://github.com/tbodt",
            avatar: "https://avatars.githubusercontent.com/u/5678977?s=40&v=4",
          },
        ],
      },
      {
        rank: 5,
        username: "imcuttle",
        repositoryName: "mometa",
        url: "https://github.com/imcuttle/mometa",
        description:
          "🛠[Beta] 面向研发的低代码元编程，代码可视编辑，辅助编码工具",
        language: "TypeScript",
        languageColor: "#2b7489",
        totalStars: 570,
        forks: 82,
        starsSince: 78,
        since: "daily",
        builtBy: [
          {
            username: "imcuttle",
            url: "https://github.com/imcuttle",
            avatar: "https://avatars.githubusercontent.com/u/13509258?s=40&v=4",
          },
        ],
      },
      {
        rank: 6,
        username: "public-apis",
        repositoryName: "public-apis",
        url: "https://github.com/public-apis/public-apis",
        description: "A collective list of free APIs",
        language: "Python",
        languageColor: "#3572A5",
        totalStars: 174786,
        forks: 20199,
        starsSince: 330,
        since: "daily",
        builtBy: [
          {
            username: "davemachado",
            url: "https://github.com/davemachado",
            avatar: "https://avatars.githubusercontent.com/u/15134885?s=40&v=4",
          },
          {
            username: "matheusfelipeog",
            url: "https://github.com/matheusfelipeog",
            avatar: "https://avatars.githubusercontent.com/u/50463866?s=40&v=4",
          },
          {
            username: "pawelborkar",
            url: "https://github.com/pawelborkar",
            avatar: "https://avatars.githubusercontent.com/u/36134699?s=40&v=4",
          },
          {
            username: "jbrooksuk",
            url: "https://github.com/jbrooksuk",
            avatar: "https://avatars.githubusercontent.com/u/246103?s=40&v=4",
          },
          {
            username: "marekdano",
            url: "https://github.com/marekdano",
            avatar: "https://avatars.githubusercontent.com/u/1914165?s=40&v=4",
          },
        ],
      },
      {
        rank: 7,
        username: "jdah",
        repositoryName: "minecraft-again",
        url: "https://github.com/jdah/minecraft-again",
        description: "yeah I made it again",
        language: "C",
        languageColor: "#555555",
        totalStars: 296,
        forks: 28,
        starsSince: 96,
        since: "daily",
        builtBy: [
          {
            username: "jdah",
            url: "https://github.com/jdah",
            avatar: "https://avatars.githubusercontent.com/u/20308439?s=40&v=4",
          },
        ],
      },
      {
        rank: 8,
        username: "mattermost",
        repositoryName: "focalboard",
        url: "https://github.com/mattermost/focalboard",
        description:
          "Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.",
        language: "TypeScript",
        languageColor: "#2b7489",
        totalStars: 7508,
        forks: 605,
        starsSince: 52,
        since: "daily",
        builtBy: [
          {
            username: "chenilim",
            url: "https://github.com/chenilim",
            avatar: "https://avatars.githubusercontent.com/u/46905241?s=40&v=4",
          },
          {
            username: "jespino",
            url: "https://github.com/jespino",
            avatar: "https://avatars.githubusercontent.com/u/290303?s=40&v=4",
          },
          {
            username: "harshilsharma63",
            url: "https://github.com/harshilsharma63",
            avatar: "https://avatars.githubusercontent.com/u/18575143?s=40&v=4",
          },
          {
            username: "sbishel",
            url: "https://github.com/sbishel",
            avatar: "https://avatars.githubusercontent.com/u/12704875?s=40&v=4",
          },
          {
            username: "asaadmahmood",
            url: "https://github.com/asaadmahmood",
            avatar: "https://avatars.githubusercontent.com/u/11034289?s=40&v=4",
          },
        ],
      },
      {
        rank: 9,
        username: "smartcontractkit",
        repositoryName: "full-blockchain-solidity-course-py",
        url: "https://github.com/smartcontractkit/full-blockchain-solidity-course-py",
        description:
          "Ultimate Solidity, Blockchain, and Smart Contract - Beginner to Expert Full Course | Python Edition",
        language: null,
        languageColor: null,
        totalStars: 5122,
        forks: 1244,
        starsSince: 131,
        since: "daily",
        builtBy: [
          {
            username: "PatrickAlphaC",
            url: "https://github.com/PatrickAlphaC",
            avatar: "https://avatars.githubusercontent.com/u/54278053?s=40&v=4",
          },
          {
            username: "cromewar",
            url: "https://github.com/cromewar",
            avatar: "https://avatars.githubusercontent.com/u/20199180?s=40&v=4",
          },
          {
            username: "jethr0null",
            url: "https://github.com/jethr0null",
            avatar: "https://avatars.githubusercontent.com/u/2119741?s=40&v=4",
          },
          {
            username: "michaelbnewman",
            url: "https://github.com/michaelbnewman",
            avatar: "https://avatars.githubusercontent.com/u/9017734?s=40&v=4",
          },
          {
            username: "chalex-eth",
            url: "https://github.com/chalex-eth",
            avatar: "https://avatars.githubusercontent.com/u/43524913?s=40&v=4",
          },
        ],
      },
      {
        rank: 10,
        username: "marktext",
        repositoryName: "marktext",
        url: "https://github.com/marktext/marktext",
        description:
          "📝A simple and elegant markdown editor, available for Linux, macOS and Windows.",
        language: "JavaScript",
        languageColor: "#f1e05a",
        totalStars: 27288,
        forks: 1955,
        starsSince: 176,
        since: "daily",
        builtBy: [
          {
            username: "Jocs",
            url: "https://github.com/Jocs",
            avatar: "https://avatars.githubusercontent.com/u/9712830?s=40&v=4",
          },
          {
            username: "fxha",
            url: "https://github.com/fxha",
            avatar: "https://avatars.githubusercontent.com/u/22716132?s=40&v=4",
          },
          {
            username: "notAlaanor",
            url: "https://github.com/notAlaanor",
            avatar: "https://avatars.githubusercontent.com/u/17591936?s=40&v=4",
          },
          {
            username: "mdogadailo",
            url: "https://github.com/mdogadailo",
            avatar: "https://avatars.githubusercontent.com/u/3466287?s=40&v=4",
          },
          {
            username: "MrHeer",
            url: "https://github.com/MrHeer",
            avatar: "https://avatars.githubusercontent.com/u/18595761?s=40&v=4",
          },
        ],
      },
      {
        rank: 11,
        username: "NVlabs",
        repositoryName: "tiny-cuda-nn",
        url: "https://github.com/NVlabs/tiny-cuda-nn",
        description: "Lightning fast & tiny C++/CUDA neural network framework",
        language: "C++",
        languageColor: "#f34b7d",
        totalStars: 544,
        forks: 39,
        starsSince: 28,
        since: "daily",
        builtBy: [
          {
            username: "Tom94",
            url: "https://github.com/Tom94",
            avatar: "https://avatars.githubusercontent.com/u/4923655?s=40&v=4",
          },
        ],
      },
      {
        rank: 12,
        username: "tauri-apps",
        repositoryName: "tauri",
        url: "https://github.com/tauri-apps/tauri",
        description:
          "Build smaller, faster, and more secure desktop applications with a web frontend.",
        language: "Rust",
        languageColor: "#dea584",
        totalStars: 28096,
        forks: 683,
        starsSince: 151,
        since: "daily",
        builtBy: [
          {
            username: "lucasfernog",
            url: "https://github.com/lucasfernog",
            avatar: "https://avatars.githubusercontent.com/u/20051258?s=40&v=4",
          },
          {
            username: "apps/renovate",
            url: "https://github.com/apps/renovate",
            avatar: "https://avatars.githubusercontent.com/in/2740?s=40&v=4",
          },
          {
            username: "renovate-bot",
            url: "https://github.com/renovate-bot",
            avatar: "https://avatars.githubusercontent.com/u/25180681?s=40&v=4",
          },
          {
            username: "jbolda",
            url: "https://github.com/jbolda",
            avatar: "https://avatars.githubusercontent.com/u/2019387?s=40&v=4",
          },
          {
            username: "nothingismagick",
            url: "https://github.com/nothingismagick",
            avatar: "https://avatars.githubusercontent.com/u/35242872?s=40&v=4",
          },
        ],
      },
      {
        rank: 13,
        username: "sivan",
        repositoryName: "heti",
        url: "https://github.com/sivan/heti",
        description:
          "赫蹏（hètí）是专为中文内容展示设计的排版样式增强。它基于通行的中文排版规范而来，可以为网站的读者带来更好的文章阅读体验。",
        language: "SCSS",
        languageColor: "#c6538c",
        totalStars: 2750,
        forks: 121,
        starsSince: 728,
        since: "daily",
        builtBy: [
          {
            username: "sivan",
            url: "https://github.com/sivan",
            avatar: "https://avatars.githubusercontent.com/u/393328?s=40&v=4",
          },
          {
            username: "apps/dependabot",
            url: "https://github.com/apps/dependabot",
            avatar: "https://avatars.githubusercontent.com/in/29110?s=40&v=4",
          },
          {
            username: "zhuangya",
            url: "https://github.com/zhuangya",
            avatar: "https://avatars.githubusercontent.com/u/499038?s=40&v=4",
          },
          {
            username: "odysa",
            url: "https://github.com/odysa",
            avatar: "https://avatars.githubusercontent.com/u/22908409?s=40&v=4",
          },
          {
            username: "leoleoasd",
            url: "https://github.com/leoleoasd",
            avatar: "https://avatars.githubusercontent.com/u/37735580?s=40&v=4",
          },
        ],
      },
      {
        rank: 14,
        username: "github",
        repositoryName: "docs",
        url: "https://github.com/github/docs",
        description: "The open-source repo for docs.github.com",
        language: "JavaScript",
        languageColor: "#f1e05a",
        totalStars: 8106,
        forks: 38579,
        starsSince: 63,
        since: "daily",
        builtBy: [
          {
            username: "Octomerger",
            url: "https://github.com/Octomerger",
            avatar: "https://avatars.githubusercontent.com/u/63058869?s=40&v=4",
          },
          {
            username: "sarahs",
            url: "https://github.com/sarahs",
            avatar: "https://avatars.githubusercontent.com/u/821071?s=40&v=4",
          },
          {
            username: "ramyaparimi",
            url: "https://github.com/ramyaparimi",
            avatar: "https://avatars.githubusercontent.com/u/33761166?s=40&v=4",
          },
          {
            username: "janiceilene",
            url: "https://github.com/janiceilene",
            avatar: "https://avatars.githubusercontent.com/u/9817819?s=40&v=4",
          },
          {
            username: "mchammer01",
            url: "https://github.com/mchammer01",
            avatar: "https://avatars.githubusercontent.com/u/42146119?s=40&v=4",
          },
        ],
      },
      {
        rank: 15,
        username: "evrimagaci",
        repositoryName: "periodum",
        url: "https://github.com/evrimagaci/periodum",
        description:
          "Periodum: Türkiye'nin ilk ve en kapsamlı kimya ve periyodik tablo projesi!",
        language: "Vue",
        languageColor: "#41b883",
        totalStars: 187,
        forks: 47,
        starsSince: 29,
        since: "daily",
        builtBy: [
          {
            username: "cagrimertbakirci",
            url: "https://github.com/cagrimertbakirci",
            avatar: "https://avatars.githubusercontent.com/u/9502185?s=40&v=4",
          },
          {
            username: "eyupcanakman",
            url: "https://github.com/eyupcanakman",
            avatar: "https://avatars.githubusercontent.com/u/1732357?s=40&v=4",
          },
          {
            username: "cangencler",
            url: "https://github.com/cangencler",
            avatar: "https://avatars.githubusercontent.com/u/27764693?s=40&v=4",
          },
          {
            username: "HKskn",
            url: "https://github.com/HKskn",
            avatar: "https://avatars.githubusercontent.com/u/1541857?s=40&v=4",
          },
        ],
      },
      {
        rank: 16,
        username: "rmcelreath",
        repositoryName: "stat_rethinking_2022",
        url: "https://github.com/rmcelreath/stat_rethinking_2022",
        description: "Statistical Rethinking course winter 2022",
        language: "R",
        languageColor: "#198CE7",
        totalStars: 2004,
        forks: 127,
        starsSince: 206,
        since: "daily",
        builtBy: [
          {
            username: "rmcelreath",
            url: "https://github.com/rmcelreath",
            avatar: "https://avatars.githubusercontent.com/u/3230381?s=40&v=4",
          },
        ],
      },
      {
        rank: 17,
        username: "GrowingGit",
        repositoryName: "GitHub-Chinese-Top-Charts",
        url: "https://github.com/GrowingGit/GitHub-Chinese-Top-Charts",
        description:
          "🇨🇳GitHub中文排行榜，各语言分离设置「软件 / 资料」榜单，精准定位中文好项目。各取所需，互不干扰，高效学习。",
        language: "Java",
        languageColor: "#b07219",
        totalStars: 43555,
        forks: 6250,
        starsSince: 157,
        since: "daily",
        builtBy: [
          {
            username: "GrowingGit",
            url: "https://github.com/GrowingGit",
            avatar: "https://avatars.githubusercontent.com/u/21018904?s=40&v=4",
          },
        ],
      },
      {
        rank: 18,
        username: "sunym1993",
        repositoryName: "flash-linux0.11-talk",
        url: "https://github.com/sunym1993/flash-linux0.11-talk",
        description:
          "你管这破玩意叫操作系统源码 — 像小说一样品读 Linux 0.11 核心代码",
        language: "C",
        languageColor: "#555555",
        totalStars: 5582,
        forks: 575,
        starsSince: 241,
        since: "daily",
        builtBy: [
          {
            username: "sunym1993",
            url: "https://github.com/sunym1993",
            avatar: "https://avatars.githubusercontent.com/u/25787738?s=40&v=4",
          },
          {
            username: "xushunke",
            url: "https://github.com/xushunke",
            avatar: "https://avatars.githubusercontent.com/u/8627326?s=40&v=4",
          },
          {
            username: "colinxu2020",
            url: "https://github.com/colinxu2020",
            avatar: "https://avatars.githubusercontent.com/u/63941938?s=40&v=4",
          },
          {
            username: "hjdokr",
            url: "https://github.com/hjdokr",
            avatar: "https://avatars.githubusercontent.com/u/60927561?s=40&v=4",
          },
          {
            username: "hdszylcd19",
            url: "https://github.com/hdszylcd19",
            avatar: "https://avatars.githubusercontent.com/u/19562544?s=40&v=4",
          },
        ],
      },
      {
        rank: 19,
        username: "ethereum",
        repositoryName: "EIPs",
        url: "https://github.com/ethereum/EIPs",
        description: "The Ethereum Improvement Proposal repository",
        language: "Solidity",
        languageColor: "#AA6746",
        totalStars: 8665,
        forks: 3154,
        starsSince: 51,
        since: "daily",
        builtBy: [
          {
            username: "eth-bot",
            url: "https://github.com/eth-bot",
            avatar: "https://avatars.githubusercontent.com/u/85952233?s=40&v=4",
          },
          {
            username: "axic",
            url: "https://github.com/axic",
            avatar: "https://avatars.githubusercontent.com/u/20340?s=40&v=4",
          },
          {
            username: "gcolvin",
            url: "https://github.com/gcolvin",
            avatar: "https://avatars.githubusercontent.com/u/16827129?s=40&v=4",
          },
          {
            username: "fulldecent",
            url: "https://github.com/fulldecent",
            avatar: "https://avatars.githubusercontent.com/u/382183?s=40&v=4",
          },
          {
            username: "Arachnid",
            url: "https://github.com/Arachnid",
            avatar: "https://avatars.githubusercontent.com/u/17865?s=40&v=4",
          },
        ],
      },
      {
        rank: 20,
        username: "ripienaar",
        repositoryName: "free-for-dev",
        url: "https://github.com/ripienaar/free-for-dev",
        description:
          "A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev",
        language: "HTML",
        languageColor: "#e34c26",
        totalStars: 52368,
        forks: 5688,
        starsSince: 140,
        since: "daily",
        builtBy: [
          {
            username: "ripienaar",
            url: "https://github.com/ripienaar",
            avatar: "https://avatars.githubusercontent.com/u/82342?s=40&v=4",
          },
          {
            username: "TraderStf",
            url: "https://github.com/TraderStf",
            avatar: "https://avatars.githubusercontent.com/u/5954335?s=40&v=4",
          },
          {
            username: "thispsj",
            url: "https://github.com/thispsj",
            avatar: "https://avatars.githubusercontent.com/u/51746608?s=40&v=4",
          },
          {
            username: "Reubend",
            url: "https://github.com/Reubend",
            avatar: "https://avatars.githubusercontent.com/u/13208038?s=40&v=4",
          },
          {
            username: "clarmso",
            url: "https://github.com/clarmso",
            avatar: "https://avatars.githubusercontent.com/u/1740517?s=40&v=4",
          },
        ],
      },
      {
        rank: 21,
        username: "godotengine",
        repositoryName: "godot",
        url: "https://github.com/godotengine/godot",
        description: "Godot Engine – Multi-platform 2D and 3D game engine",
        language: "C++",
        languageColor: "#f34b7d",
        totalStars: 45587,
        forks: 8222,
        starsSince: 97,
        since: "daily",
        builtBy: [
          {
            username: "akien-mga",
            url: "https://github.com/akien-mga",
            avatar: "https://avatars.githubusercontent.com/u/4701338?s=40&v=4",
          },
          {
            username: "reduz",
            url: "https://github.com/reduz",
            avatar: "https://avatars.githubusercontent.com/u/6265307?s=40&v=4",
          },
          {
            username: "Calinou",
            url: "https://github.com/Calinou",
            avatar: "https://avatars.githubusercontent.com/u/180032?s=40&v=4",
          },
          {
            username: "Chaosus",
            url: "https://github.com/Chaosus",
            avatar: "https://avatars.githubusercontent.com/u/3036176?s=40&v=4",
          },
          {
            username: "neikeq",
            url: "https://github.com/neikeq",
            avatar: "https://avatars.githubusercontent.com/u/7718100?s=40&v=4",
          },
        ],
      },
      {
        rank: 22,
        username: "hannahcode",
        repositoryName: "wordle",
        url: "https://github.com/hannahcode/wordle",
        description:
          "A clone of the popular game Wordle made using React, Typescript, and Tailwind",
        language: "TypeScript",
        languageColor: "#2b7489",
        totalStars: 182,
        forks: 81,
        starsSince: 29,
        since: "daily",
        builtBy: [
          {
            username: "hannahcode",
            url: "https://github.com/hannahcode",
            avatar: "https://avatars.githubusercontent.com/u/70654324?s=40&v=4",
          },
          {
            username: "gbear605",
            url: "https://github.com/gbear605",
            avatar: "https://avatars.githubusercontent.com/u/690716?s=40&v=4",
          },
          {
            username: "pip8786",
            url: "https://github.com/pip8786",
            avatar: "https://avatars.githubusercontent.com/u/1085106?s=40&v=4",
          },
          {
            username: "craigp1231",
            url: "https://github.com/craigp1231",
            avatar: "https://avatars.githubusercontent.com/u/4073362?s=40&v=4",
          },
          {
            username: "jnsturgis",
            url: "https://github.com/jnsturgis",
            avatar: "https://avatars.githubusercontent.com/u/10157451?s=40&v=4",
          },
        ],
      },
      {
        rank: 23,
        username: "opsdisk",
        repositoryName: "the_cyber_plumbers_handbook",
        url: "https://github.com/opsdisk/the_cyber_plumbers_handbook",
        description: "Free copy of The Cyber Plumber's Handbook",
        language: null,
        languageColor: null,
        totalStars: 1429,
        forks: 90,
        starsSince: 256,
        since: "daily",
        builtBy: [
          {
            username: "opsdisk",
            url: "https://github.com/opsdisk",
            avatar: "https://avatars.githubusercontent.com/u/8660252?s=40&v=4",
          },
        ],
      },
      {
        rank: 24,
        username: "Cerbersec",
        repositoryName: "Ares",
        url: "https://github.com/Cerbersec/Ares",
        description:
          "Project Ares is a Proof of Concept (PoC) loader written in C/C++ based on the Transacted Hollowing technique",
        language: "C",
        languageColor: "#555555",
        totalStars: 155,
        forks: 29,
        starsSince: 23,
        since: "daily",
        builtBy: [
          {
            username: "Cerbersec",
            url: "https://github.com/Cerbersec",
            avatar: "https://avatars.githubusercontent.com/u/58052983?s=40&v=4",
          },
        ],
      },
      {
        rank: 25,
        username: "aseprite",
        repositoryName: "aseprite",
        url: "https://github.com/aseprite/aseprite",
        description:
          "Animated sprite editor & pixel art tool (Windows, macOS, Linux)",
        language: "C++",
        languageColor: "#f34b7d",
        totalStars: 15722,
        forks: 1389,
        starsSince: 132,
        since: "daily",
        builtBy: [
          {
            username: "dacap",
            url: "https://github.com/dacap",
            avatar: "https://avatars.githubusercontent.com/u/39654?s=40&v=4",
          },
          {
            username: "Gasparoken",
            url: "https://github.com/Gasparoken",
            avatar: "https://avatars.githubusercontent.com/u/32165475?s=40&v=4",
          },
          {
            username: "rautesamtr",
            url: "https://github.com/rautesamtr",
            avatar: "https://avatars.githubusercontent.com/u/1131371?s=40&v=4",
          },
          {
            username: "zed9h",
            url: "https://github.com/zed9h",
            avatar: "https://avatars.githubusercontent.com/u/7734?s=40&v=4",
          },
          {
            username: "lampysprites",
            url: "https://github.com/lampysprites",
            avatar: "https://avatars.githubusercontent.com/u/49268426?s=40&v=4",
          },
        ],
      },
    ]);
    setTrendingDeveloper([
      {
        rank: 1,
        username: "jesseduffield",
        name: "Jesse Duffield",
        url: "https://github.com/jesseduffield",
        avatar: "https://avatars.githubusercontent.com/u/8456633?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "lazygit",
          description: null,
          url: "https://github.com/jesseduffield/lazygit",
        },
      },
      {
        rank: 2,
        username: "ornicar",
        name: "Thibault Duplessis",
        url: "https://github.com/ornicar",
        avatar: "https://avatars.githubusercontent.com/u/140370?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "lila",
          description: null,
          url: "https://github.com/ornicar/lila",
        },
      },
      {
        rank: 3,
        username: "danielroe",
        name: "Daniel Roe",
        url: "https://github.com/danielroe",
        avatar: "https://avatars.githubusercontent.com/u/28706372?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "typed-vuex",
          description: null,
          url: "https://github.com/danielroe/typed-vuex",
        },
      },
      {
        rank: 4,
        username: "giampaolo",
        name: "Giampaolo Rodola",
        url: "https://github.com/giampaolo",
        avatar: "https://avatars.githubusercontent.com/u/681260?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "psutil",
          description: null,
          url: "https://github.com/giampaolo/psutil",
        },
      },
      {
        rank: 5,
        username: "stof",
        name: "Christophe Coevoet",
        url: "https://github.com/stof",
        avatar: "https://avatars.githubusercontent.com/u/439401?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "StofDoctrineExtensionsBundle",
          description: null,
          url: "https://github.com/stof/StofDoctrineExtensionsBundle",
        },
      },
      {
        rank: 6,
        username: "SanderMertens",
        name: "Sander Mertens",
        url: "https://github.com/SanderMertens",
        avatar: "https://avatars.githubusercontent.com/u/9919222?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "flecs",
          description: null,
          url: "https://github.com/SanderMertens/flecs",
        },
      },
      {
        rank: 7,
        username: "PySimpleGUI",
        name: "PySimpleGUI",
        url: "https://github.com/PySimpleGUI",
        avatar: "https://avatars.githubusercontent.com/u/46163555?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "PySimpleGUI",
          description: null,
          url: "https://github.com/PySimpleGUI/PySimpleGUI",
        },
      },
      {
        rank: 8,
        username: "unknwon",
        name: "Joe Chen",
        url: "https://github.com/unknwon",
        avatar: "https://avatars.githubusercontent.com/u/2946214?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "the-way-to-go_ZH_CN",
          description: null,
          url: "https://github.com/unknwon/the-way-to-go_ZH_CN",
        },
      },
      {
        rank: 9,
        username: "JanDeDobbeleer",
        name: "Jan De Dobbeleer",
        url: "https://github.com/JanDeDobbeleer",
        avatar: "https://avatars.githubusercontent.com/u/2492783?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "oh-my-posh",
          description: null,
          url: "https://github.com/JanDeDobbeleer/oh-my-posh",
        },
      },
      {
        rank: 10,
        username: "sibelius",
        name: "Sibelius Seraphini",
        url: "https://github.com/sibelius",
        avatar: "https://avatars.githubusercontent.com/u/2005841?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "ccsseraphini",
          description: null,
          url: "https://github.com/sibelius/ccsseraphini",
        },
      },
      {
        rank: 11,
        username: "Saul-Mirone",
        name: "Mirone",
        url: "https://github.com/Saul-Mirone",
        avatar: "https://avatars.githubusercontent.com/u/10047788?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "milkdown",
          description: null,
          url: "https://github.com/Saul-Mirone/milkdown",
        },
      },
      {
        rank: 12,
        username: "AlvaroBrey",
        name: "Álvaro Brey",
        url: "https://github.com/AlvaroBrey",
        avatar: "https://avatars.githubusercontent.com/u/8677743?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "alvarobrey.github.io",
          description: null,
          url: "https://github.com/AlvaroBrey/alvarobrey.github.io",
        },
      },
      {
        rank: 13,
        username: "nschloe",
        name: "Nico Schlömer",
        url: "https://github.com/nschloe",
        avatar: "https://avatars.githubusercontent.com/u/181628?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "tiptop",
          description: null,
          url: "https://github.com/nschloe/tiptop",
        },
      },
      {
        rank: 14,
        username: "ospfranco",
        name: "Oscar Franco",
        url: "https://github.com/ospfranco",
        avatar: "https://avatars.githubusercontent.com/u/1634213?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "sol",
          description: null,
          url: "https://github.com/ospfranco/sol",
        },
      },
      {
        rank: 15,
        username: "jennybc",
        name: "Jennifer (Jenny) Bryan",
        url: "https://github.com/jennybc",
        avatar: "https://avatars.githubusercontent.com/u/599454?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "jadd",
          description: null,
          url: "https://github.com/jennybc/jadd",
        },
      },
      {
        rank: 16,
        username: "binwiederhier",
        name: "Philipp C. Heckel",
        url: "https://github.com/binwiederhier",
        avatar: "https://avatars.githubusercontent.com/u/664597?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "ntfy",
          description: null,
          url: "https://github.com/binwiederhier/ntfy",
        },
      },
      {
        rank: 17,
        username: "yairm210",
        name: "Yair Morgenstern",
        url: "https://github.com/yairm210",
        avatar: "https://avatars.githubusercontent.com/u/8366208?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "Unciv",
          description: null,
          url: "https://github.com/yairm210/Unciv",
        },
      },
      {
        rank: 18,
        username: "wing328",
        name: "William Cheng",
        url: "https://github.com/wing328",
        avatar: "https://avatars.githubusercontent.com/u/934260?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: null,
          description: null,
          url: null,
        },
      },
      {
        rank: 19,
        username: "argyleink",
        name: "Adam Argyle",
        url: "https://github.com/argyleink",
        avatar: "https://avatars.githubusercontent.com/u/1134620?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "open-props",
          description: null,
          url: "https://github.com/argyleink/open-props",
        },
      },
      {
        rank: 20,
        username: "Gabriel439",
        name: "Gabriella Gonzalez",
        url: "https://github.com/Gabriel439",
        avatar: "https://avatars.githubusercontent.com/u/1313787?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "post-rfc",
          description: null,
          url: "https://github.com/Gabriel439/post-rfc",
        },
      },
      {
        rank: 21,
        username: "jsoref",
        name: "Josh Soref",
        url: "https://github.com/jsoref",
        avatar: "https://avatars.githubusercontent.com/u/2119212?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: null,
          description: null,
          url: null,
        },
      },
      {
        rank: 22,
        username: "felangel",
        name: "Felix Angelov",
        url: "https://github.com/felangel",
        avatar: "https://avatars.githubusercontent.com/u/8855632?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "bloc",
          description: null,
          url: "https://github.com/felangel/bloc",
        },
      },
      {
        rank: 23,
        username: "bcoe",
        name: "Benjamin E. Coe",
        url: "https://github.com/bcoe",
        avatar: "https://avatars.githubusercontent.com/u/194609?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "c8",
          description: null,
          url: "https://github.com/bcoe/c8",
        },
      },
      {
        rank: 24,
        username: "burhanrashid52",
        name: "Burhanuddin Rashid",
        url: "https://github.com/burhanrashid52",
        avatar: "https://avatars.githubusercontent.com/u/14251963?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "PhotoEditor",
          description: null,
          url: "https://github.com/burhanrashid52/PhotoEditor",
        },
      },
      {
        rank: 25,
        username: "adiwajshing",
        name: "Adhiraj Singh",
        url: "https://github.com/adiwajshing",
        avatar: "https://avatars.githubusercontent.com/u/8328864?s=96&v=4",
        since: "daily",
        popularRepository: {
          repositoryName: "Baileys",
          description: null,
          url: "https://github.com/adiwajshing/Baileys",
        },
      },
    ]);
  }, []);
  return (
    <div>
      <Header />
      <TrendingList
        trendingRepo={trendingRepo?.length ? trendingRepo : []}
        trendingDeveloper={trendingDeveloper?.length ? trendingDeveloper : []}
      />
    </div>
  );
}
